### PR TITLE
feat: 🎸 Add UM5302TA layout

### PR DESCRIPTION
**Pull request by vazw**
- [x] Tested on Voidlinux Sway (Wayland) kernel 6.1.83_1_LTS

### CODE REVIEW

**Review by kamack38 — COMMENTED** [review]
You should also add the layout to the README

**Comment by vazw** [comment]
> You should also add the layout to the README

Here it it!

**Comment by iamkroot** [comment]
I don't see any difference from the `m433ia` layout. Why not just use that?

**Comment by vazw** [comment]
Oh well.. just realized there is the same layout. I don't known what i was thinking back then 😂 sorry for washing your precious time🙏

**Pull request closed without merging**
